---
    title: 
        ru: (Не)типичная жизнь
        en: (Un)typical life
        common: (Un)typical life
        
    description: 
        ru: "История бывает разной: грустной, повседневной, романтической, детективной... Моя же будет (не)обычной."
        en: "The story can be different: sad, casual, romantic, detective... Mine will be (un)usual."
        common: "The story can be different: sad, casual, romantic, detective... Mine will be (un)usual."
        
    version: 1.0
    cover: base.png