---
    title: 
        ru: Типичная жизнь
        en: Typical life
        common: Typical life
        
    description: 
        ru: "История бывает разной: грустной, повседневной, романтической, детективной... Моя же будет самой обычной, но с небольшим подвохом."
        en: "The story can be different: sad, everyday, romantic, detective... Mine will be the most ordinary, but with a little catch."
        common: "The story can be different: sad, everyday, romantic, detective... Mine will be the most ordinary, but with a little catch."
        
    version: 1.0
    cover: base.png